# Generated by Django 3.2.8 on 2021-11-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211105_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
